//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlasePodataka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dokumentacija
    {
        public int IDDokumentacije { get; set; }
        public int IDZahteva { get; set; }
        public string NazivDokumenta { get; set; }
        public bool Dostavljeno { get; set; }
    
        public virtual Zahtev Zahtev { get; set; }
    }
}
