//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicnaKarta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gradjanin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gradjanin()
        {
            this.Zahtevs = new HashSet<Zahtev>();
        }
    
        public string JMBG { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public System.DateTime DatumRodjenja { get; set; }
        public string Pol { get; set; }
        public string Drzavljanstvo { get; set; }
        public string AdresaPrebivalista { get; set; }
        public string KontaktTelefon { get; set; }
        public string Email { get; set; }
        public string BrojStareLK { get; set; }
        public Nullable<System.DateTime> DatumIstekaLK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zahtev> Zahtevs { get; set; }
    }
}
