//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicnaKarta
{
    using System;
    using System.Collections.Generic;
    
    public partial class IstorijaStatusaZahteva
    {
        public int IDIstorije { get; set; }
        public int IDZahteva { get; set; }
        public string StariStatus { get; set; }
        public string NoviStatus { get; set; }
        public System.DateTime DatumPromene { get; set; }
        public string Korisnik { get; set; }
        public string Napomena { get; set; }
    
        public virtual Zahtev Zahtev { get; set; }
    }
}
