//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicnaKarta
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RVS2026LicnaKartaV1Entities : DbContext
    {
        public RVS2026LicnaKartaV1Entities()
            : base("name=RVS2026LicnaKartaV1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dokumentacija> Dokumentacijas { get; set; }
        public virtual DbSet<Gradjanin> Gradjanins { get; set; }
        public virtual DbSet<IstorijaStatusaZahteva> IstorijaStatusaZahtevas { get; set; }
        public virtual DbSet<Korisnik> Korisniks { get; set; }
        public virtual DbSet<RoditeljStaratelj> RoditeljStarateljs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Zahtev> Zahtevs { get; set; }
    }
}
