//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicnaKarta
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoditeljStaratelj
    {
        public int IDRoditelja { get; set; }
        public int IDZahteva { get; set; }
        public string ImePrezime { get; set; }
        public string JMBG { get; set; }
        public string Srodstvo { get; set; }
        public string KontaktTelefon { get; set; }
        public string Email { get; set; }
    
        public virtual Zahtev Zahtev { get; set; }
    }
}
