//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicnaKarta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zahtev
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zahtev()
        {
            this.Dokumentacijas = new HashSet<Dokumentacija>();
            this.IstorijaStatusaZahtevas = new HashSet<IstorijaStatusaZahteva>();
            this.RoditeljStarateljs = new HashSet<RoditeljStaratelj>();
        }
    
        public int IDZahteva { get; set; }
        public string JMBGGradjanina { get; set; }
        public System.DateTime DatumPodnosenja { get; set; }
        public string RazlogIzdavanja { get; set; }
        public string TipZahteva { get; set; }
        public string MestoPodnosenja { get; set; }
        public string StatusZahteva { get; set; }
        public string Napomena { get; set; }
        public string BrojNoveLK { get; set; }
        public Nullable<System.DateTime> DatumIstekaNoveLK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dokumentacija> Dokumentacijas { get; set; }
        public virtual Gradjanin Gradjanin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IstorijaStatusaZahteva> IstorijaStatusaZahtevas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoditeljStaratelj> RoditeljStarateljs { get; set; }
    }
}
